CREATE TABLE DEPARTMENT
(
    ID              BIGINT       NOT NULL,
    DEPARTMENT_NAME VARCHAR(255) NOT NULL,
    LOCATION_ID     BIGINT       NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE DEPARTMENT
    ADD CONSTRAINT FK_DEPARTMENT_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID)
