CREATE TABLE EMPLOYEE
(
    ID            BIGINT AUTO_INCREMENT NOT NULL,
    FIRST_NAME    VARCHAR(255) NOT NULL,
    LAST_NAME     VARCHAR(255) NOT NULL,
    EMAIL         VARCHAR(255),
    PHONE_NUMBER  VARCHAR(255) NOT NULL,
    HIRE_DATE     DATE         NOT NULL,
    SALARY        BIGINT       NOT NULL,
    JOB_ID        BIGINT,
    MANAGER_ID    BIGINT,
    DEPARTMENT_ID BIGINT,
    PRIMARY KEY (ID)
);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB (ID);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE (ID);
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID);