CREATE TABLE DEPENDENT
(
    ID           BIGINT AUTO_INCREMENT NOT NULL,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    RELATIONSHIP SMALLINT     NOT NULL,
    EMPLOYEE_ID  BIGINT       NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE DEPENDENT
    ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID);